"""modif user add password

Revision ID: 065390c05208
Revises: 69406252980b
Create Date: 2025-02-26 13:35:09.875110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065390c05208'
down_revision = '69406252980b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
