"""syncro

Revision ID: 0768f1e10b64
Revises: 1c91881626a7
Create Date: 2025-02-28 11:04:28.046834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0768f1e10b64'
down_revision = '1c91881626a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receptions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receptions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('magasin', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fournisseur', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('date_reception', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
