"""modif products remove description

Revision ID: 1c91881626a7
Revises: 065390c05208
Create Date: 2025-02-26 14:55:25.900017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c91881626a7'
down_revision = '065390c05208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
