"""modif user add prenom

Revision ID: 69406252980b
Revises: 1b4c20f3fa80
Create Date: 2025-02-26 11:42:19.783532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69406252980b'
down_revision = '1b4c20f3fa80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prenom', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('prenom')

    # ### end Alembic commands ###
