"""empty message

Revision ID: 78ca430b264e
Revises: 
Create Date: 2025-02-23 13:56:28.591803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ca430b264e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix_de_vente', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prix_unitaire', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('prix_unitaire')
        batch_op.drop_column('prix_de_vente')

    # ### end Alembic commands ###
