"""modif supplier

Revision ID: a616fd7f1163
Revises: e983668aea1d
Create Date: 2025-03-13 23:03:50.085695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a616fd7f1163'
down_revision = 'e983668aea1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.drop_column('fournisseur_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fournisseur_id', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
