"""add recep item

Revision ID: e983668aea1d
Revises: 87d93b4db40a
Create Date: 2025-03-13 23:02:45.702148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e983668aea1d'
down_revision = '87d93b4db40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fournisseur_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_reception', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_montant', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('receptions_ibfk_1', type_='foreignkey')
        batch_op.drop_column('quantite')
        batch_op.drop_column('supplier')
        batch_op.drop_column('product_id')
        batch_op.drop_column('montant')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('montant', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('supplier', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('quantite', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('receptions_ibfk_1', 'products', ['product_id'], ['id'])
        batch_op.drop_column('statut')
        batch_op.drop_column('total_montant')
        batch_op.drop_column('date_reception')
        batch_op.drop_column('fournisseur_id')

    # ### end Alembic commands ###
