"""supplier

Revision ID: f785968b2780
Revises: a616fd7f1163
Create Date: 2025-03-13 23:05:47.537192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f785968b2780'
down_revision = 'a616fd7f1163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.drop_column('statut')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
